### PR TITLE
implement front-end

### PR DESCRIPTION
**Pull request by StevenJNPearce**
Fixes: https://github.com/MyBitFoundation/MyBit-Network.tech/issues/148

URL: https://friendly-borg-822cca.netlify.com/
Choose ropsten network in Metamask.

Changes from Trust app/ other points of note:
1) Got rid of all the boilerplate bloat/junk - there was allot of it!
2) Uses the new way of Metamask requesting access, see: [](https://bit.ly/2QQHXvF)
3) Cleaned up much promise spaghetti like `async (address, network) => new Promise(async (resolve, reject) =>...`
4) Some changes in Payroll.sol that were needed to get the app functional. 

@jjperezaguinaga @PeterMPhillips @kyledewy

### CODE REVIEW

**Comment by 0xjjpa** [comment]
@StevenJNPearce Looking good! I'm going to migrate the bounty from https://github.com/MyBitFoundation/MyBit-Network.tech/issues/148 to this repository and its bounty to Gitcoin, but only you'll be approved on it ☺️ .

Please reapply with this PR after that! Thanks!
cc @cryptnotiq @kyledewy @csmartinsfct Please take a minute to review this PR ☺️

**Comment by StevenJNPearce** [comment]
@jjperezaguinaga Good to hear; I'm a big fan of Gitcoin, have completed 20 bounties there already.

**Comment by StevenJNPearce** [comment]
Any progress on getting this PR reviewed? I'm worried with Christmas just around the corner, the bounty wont get paid out until after the 2nd token sale has started, which may have caused a reduction in dollar value. Sorry to sound impatient, but my motivation is as much financial as it is this being a cool project I enjoy working on :-)

**Comment by mybit-coordinator** [comment]
@StevenJNPearce totally understandable, and we are very sorry this wasn't the case. We are taking a look at this now and hopefully we can get a solution on quite soon. Will keep you posted.

**Pull request merged**
